### ISSUE TITLE
`typescript-express-example-server-generator`: `Object is possibly 'null'`.

### ISSUE THREAD

**Issue by kindaro** [karlvr/openapi-generator-plus-generators#16]
## See for yourself.

```
cd /tmp
mkdir openapi
cd openapi
npm init -y
npm install openapi-generator-plus @openapi-generator-plus/typescript-express-example-server-generator express @types/express ts-node
wget 'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml'
npx openapi-generator-plus -g @openapi-generator-plus/typescript-express-example-server-generator -o . petstore.yaml
npx ts-node index.ts
```

## Expected behaviour.

A server starts up.

## Actual behaviour.

The following error appears:

```
/tmp/openapi/node_modules/ts-node/src/index.ts:693
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts:33:30 - error TS2531: Object is possibly 'null'.

33  console.log(`Listening on ${address.port}`)
                                ~~~~~~~
index.ts:33:38 - error TS2339: Property 'port' does not exist on type 'string | AddressInfo'.
  Property 'port' does not exist on type 'string'.

33  console.log(`Listening on ${address.port}`)
                                        ~~~~

    at createTSError (/tmp/openapi/node_modules/ts-node/src/index.ts:693:12)
    at reportTSError (/tmp/openapi/node_modules/ts-node/src/index.ts:697:19)
    at getOutput (/tmp/openapi/node_modules/ts-node/src/index.ts:884:36)
    at Object.compile (/tmp/openapi/node_modules/ts-node/src/index.ts:1186:30)
    at Module.m._compile (/tmp/openapi/node_modules/ts-node/src/index.ts:1310:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Object.require.extensions.<computed> [as .ts] (/tmp/openapi/node_modules/ts-node/src/index.ts:1314:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  diagnosticText: "\x1B[96mindex.ts\x1B[0m:\x1B[93m33\x1B[0m:\x1B[93m30\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2531: \x1B[0mObject is possibly 'null'.\n" +
    '\n' +
    '\x1B[7m33\x1B[0m  console.log(`Listening on ${address.port}`)\n' +
    '\x1B[7m  \x1B[0m \x1B[91m                             ~~~~~~~\x1B[0m\n' +
    "\x1B[96mindex.ts\x1B[0m:\x1B[93m33\x1B[0m:\x1B[93m38\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2339: \x1B[0mProperty 'port' does not exist on type 'string | AddressInfo'.\n" +
    "  Property 'port' does not exist on type 'string'.\n" +
    '\n' +
    '\x1B[7m33\x1B[0m  console.log(`Listening on ${address.port}`)\n' +
    '\x1B[7m  \x1B[0m \x1B[91m                                     ~~~~\x1B[0m\n',
  diagnosticCodes: [ 2531, 2339 ]
}
```

## Discussion.

See this code:

https://github.com/karlvr/openapi-generator-plus-generators/blob/9dc8bfd8c58431704bbf3d1d9cc3cce156592f8f/packages/typescript-express-example-server/templates/index.hbs#L46-L50

How can one possibly use the value `server` before it is defined, even inside its own definition? Surely this is an error. After removing the mentions of `server`, everything works, even though we cannot print the address anymore.

The corrected code:

```
const port = options.port || 3000
const server = app.listen(port, function() {
	console.log(`Listening on ${port}`)
})
```

**Comment by karlvr** [comment]
@kindaro thanks for raising the issue, you're quite right. I haven't poured _any_ love into this generator. I'm adding some basic testing so the code is at least compiled. It's revealing a few deficiencies...

But, it is OK to reference `server` inside that callback, as the callback is asynchronous. It sure looks weird. I don't love it. But it seems like it's a thing people do. I'm not sure what was going on that prevented you from compiling it...

I wonder what version of node and TypeScript you're using? I am using node 14.17.5 and TypeScript 4.3.5. The generator will actually generate a `package.json` if you include an `npm` key in the configuration. 

I've pushed a fix in eea6b35d0e3d31c6f3d9541ee926f37b95f5e58b. I haven't released it yet, but I will do so soon. I'd love to know the versions you're using as above.

**Comment by kindaro** [comment]
These are the relevant versions:

```
% npm view '@openapi-generator-plus/typescript-express-example-server-generator' version
0.15.0
% npm view 'typescript' version
4.3.5
% node --version
v16.4.2
```

You are right that `server` can be used this way and my understanding of the cause of the error was wrong — this is merely a type error. Your solution solves it partially. I tried to make it work from your updated commit but I still see a type error:

```
% npx ts generated/index.ts
Build failed:
generated/index.ts:36:31 - error TS2531: Object is possibly 'null'.

36  	console.log(`Listening on ${address.port}`)
    	                            ~~~~~~~
generated/index.ts:36:31 - error TS2531: Object is possibly 'null'.

36  	console.log(`Listening on ${address.port}`)
    	                            ~~~~~~~
```

So, it seems that there are actually 3 cases to handle:

*  `server` being a string — handled.
* `server` being an object with a field `port` — handled.
* `server` being `null` — not handled.

**Comment by karlvr** [comment]
@kindaro thanks for that. I guess the `Server` has added `null` in a later node version! Hopefully resolved in `002028c600edee8adcaef912020023873896b71b`.

**Comment by kindaro** [comment]
It works. No more errors.
